<h1><?php Helper::translate($_COOKIE['language'],"aircraftpitch") ?></h1>
<form method="POST">
    <div class="form-group">
        <label for="r"><?php Helper::translate($_COOKIE['language'],"raircraft") ?></label>
        <input type="number" class="form-control" name="r" id="r" required autocomplete="off">
    </div>
    <div class="form-group">
        <label for="time"><?php Helper::translate($_COOKIE['language'],"graphtime") ?></label>
        <input type="range" class="form-control" name="time" id="time" min="5" max="20" step="0.05" value="5" onchange="changeTime(this.value)" required>
        <p id="timetext"></p>
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="animation" name="animation" value="1" checked>
        <label for="animation"><?php Helper::translate($_COOKIE['language'],"animation") ?></label>
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="graph" name="graph" value="1" checked>
        <label for="graph"><?php Helper::translate($_COOKIE['language'],"graph") ?></label>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" name="send" value="<?php Helper::translate($_COOKIE['language'],'send') ?>">
    </div>
</form>
<?php
if(isset($_POST['send'])):
    Db::$medoo->update("stats",["visitors[+]" => 1],["page_name"=>"aircraftpitch"]);
    $ir = trim($_POST['r']);
    $arrContextOptions=array(
        "ssl"=>array(
            "verify_peer"=>false,
            "verify_peer_name"=>false,
        ),
        'http' => array('ignore_errors' => true),
    );
    $arr = file_get_contents("https://localhost:443/final/api.php?key=KHt9t83cmV6pfcyfSbcB9jyG7TnJMySYT28CUv2jSMN9RrNj&model=aircraftpitch&r={$ir}&position={$_SESSION['aircraft']}", false, stream_context_create($arrContextOptions));
    $arr = json_decode($arr, true);
    $time = (isset($_POST['time'])) ? $_POST['time']*1000 : "5000";
    $animation = (isset($_POST['animation'])) ? '; animation' : '';
    $graph = (isset($_POST['graph'])) ? '; graph' : '';
    Db::$medoo->insert("commands",[
      "command"=>"Aircraft pitch -> r = " . $_POST['r'] . $animation . $graph,
      "output"=> gettype($arr),
      "success" => "1"
    ]);
    $_SESSION['aircraft'] = $arr['continue'];
    if(isset($_POST['animation']) && $_POST['animation'] = 1): ?>
        <div id='animationContainer' class="animation"></div>
        <script>
            // nastavenie dlzky animacie
            var time = <?= $time ?>;

            let x, y, baseSize, counter = 0;
            var interval;
            let plane_angle = 0;
            let pitch_angle = 0;
            var plane_data = <?= json_encode($arr['plane']); ?>;
            var pitch_data = <?= json_encode($arr['pitch']); ?>;

            function startInterval(){
              interval = setInterval(function(){
                intervalRedraw();
              }, time/plane_data.length);
            }

            function intervalRedraw() {
              plane_angle = plane_data[counter]['y'];
              pitch_angle = pitch_data[counter]['y'];
              redraw();
              counter++;
              if (counter == plane_data.length) {
                clearInterval(interval);
              }
            }

            function preload() {
              plane_model = loadImage('https://147.175.121.210:4480/final/public/img/models/airplane.svg');
              pitch_model = loadImage('https://147.175.121.210:4480/final/public/img/models/airplane-back.svg');
            }

            function setup() {
              var width = document.getElementById('animationContainer').offsetWidth;
              let myCanvas = createCanvas(width, 300);
              myCanvas.parent('animationContainer');
              baseSize = height * 0.6;
              x = width * 0.5;
              y = height * 0.5;
              startInterval();
            }

            function draw() {
              clear();
              push();
              airplane(x,y,radians(plane_angle));
              airplaneBack(baseSize*0.53, 0, radians(pitch_angle));
              pop();
            }

            function airplane(x,y,rot){
              translate(x,y,rot);
              rotate(rot);
              image(plane_model, -baseSize, -(baseSize*0.57), baseSize*2, baseSize);
            }

            function airplaneBack(x, y, rot) {
              translate(x, y);
              rotate(rot);
              image(pitch_model,0,0,baseSize*0.17,baseSize*0.02);
            }

            function windowResized() {
              resizeCanvas(windowWidth, windowHeight);
            }
        </script>
    <?php endif;
    if(isset($_POST['graph']) && $_POST['graph'] = 1): ?>
        <div id="chart" class="graph"></div>
        <script>
            var chart = new CanvasJS.Chart("chart", {
                animationEnabled: true,
                animationDuration: <?= $time ?>,
                exportEnabled: true,
                theme: "dark2", // "light1", "light2", "dark1", "dark2"
                zoomEnabled: true,
                title:{
                    text: "<?php Helper::translate($_COOKIE["language"],"aircraftpitch") ?>"
                },
                data: [{
                    type: "line", //change type to bar, line, area, pie, etc
                    //indexLabel: "{y}", //Shows y value on all Data Points
                    indexLabelFontColor: "#5487c1",
                    indexLabelPlacement: "outside",
                    lineColor: "#5487c1",
                    dataPoints: [{x:0,y:0}]
                },{
                    type: "line", //change type to bar, line, area, pie, etc
                    //indexLabel: "{y}", //Shows y value on all Data Points
                    indexLabelFontColor: "#dc8e39",
                    indexLabelPlacement: "outside",
                    lineColor: "#dc8e39",
                    dataPoints: [{x:0,y:0}]
                }]
            });

            chart.options.data[0].dataPoints = <?= json_encode($arr['plane']); ?>;
            chart.options.data[1].dataPoints = <?= json_encode($arr['pitch']); ?>;
            chart.render();
        </script>
    <?php endif; ?>
<?php endif;?>
