<?php Db::$medoo->update("stats",["visitors[+]" => 1],["page_name"=>"aircraftpitch"])?>
<h1><?php Helper::translate($_COOKIE['language'],"aircraftpitch") ?></h1>
<form method="POST">
    <div class="form-group">
        <label for="planeangle"><?php Helper::translate($_COOKIE['language'],"planeangle") ?></label>
        <input type="number" class="form-control" name="planeangle" id="planeangle" required>
    </div>
    <div class="form-group">
        <label for="backangle"><?php Helper::translate($_COOKIE['language'],"backangle") ?></label>
        <input type="number" class="form-control" name="backangle" id="backangle" required>
    </div>
    <div class="form-group">
        <label for="r">r</label>
        <input type="number" class="form-control" name="r" id="r" required>
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="animation" name="animation" value="1" checked>
        <label for="animation"><?php Helper::translate($_COOKIE['language'],"animation") ?></label>
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="graph" name="graph" value="1" checked>
        <label for="graph"><?php Helper::translate($_COOKIE['language'],"graph") ?></label>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" name="send" value="<?php Helper::translate($_COOKIE['language'],'send') ?>">
    </div>
</form>
<?php
if(isset($_POST['send'])):
    $ir = trim($_POST['r']); $ipa = trim($_POST['planeangle']); $ipa = trim($_POST['backangle']);
    $arrContextOptions=array(
        "ssl"=>array(
            "verify_peer"=>false,
            "verify_peer_name"=>false,
        ),
        'http' => array('ignore_errors' => true),
    );
    $arr = file_get_contents("https://localhost:443/final/api.php?key=KHt9t83cmV6pfcyfSbcB9jyG7TnJMySYT28CUv2jSMN9RrNj&model=suspension&r={$ir}&plane={$iwp}&pitch={$icp}", false, stream_context_create($arrContextOptions));
    $arr = json_decode($arr, true);
    if(isset($_POST['graph']) && $_POST['graph'] = 1): ?>
        <div id="chart" class="graph"></div>
        <script>
            var chart = new CanvasJS.Chart("chart", {
                animationEnabled: true,
                exportEnabled: true,
                theme: "dark2", // "light1", "light2", "dark1", "dark2"
                zoomEnabled: true,
                title:{
                    text: "<?php Helper::translate($_COOKIE["language"],"aircraftpitch") ?>"
                },
                data: [{
                    type: "line", //change type to bar, line, area, pie, etc
                    //indexLabel: "{y}", //Shows y value on all Data Points
                    indexLabelFontColor: "#5487c1",
                    indexLabelPlacement: "outside",
                    lineColor: "#5487c1",
                    dataPoints: [{x:0,y:0}]
                },{
                    type: "line", //change type to bar, line, area, pie, etc
                    //indexLabel: "{y}", //Shows y value on all Data Points
                    indexLabelFontColor: "#dc8e39",
                    indexLabelPlacement: "outside",
                    lineColor: "#dc8e39",
                    dataPoints: [{x:0,y:0}]
                }]
            });

            chart.options.data[0].dataPoints = <?= json_encode($arr['plane']); ?>;
            chart.options.data[1].dataPoints = <?= json_encode($arr['pitch']); ?>;
            chart.render();
        </script>
    <?php endif;
    if(isset($_POST['animation']) && $_POST['animation'] = 1): ?>
        <div id='animationContainer' class="animation"></div>
        <script>
            // nastavenie dlzky animacie
            var time = 5000;

            let plane_angle = 0;
            let pitch_angle = 0;
            var plane = <?= json_encode($arr['plane']); ?>;
            var pitch = <?= json_encode($arr['pitch']); ?>;
            let x, y, baseSize, counter = 0;
            var interval;

            function startInterval(){
              interval = setInterval(function(){
                intervalRedraw();
              }, time/plane.length);
            }

            function intervalRedraw() {
              plane_angle = plane[counter]['y'];
              pitch_angle = pitch[counter]['y'];
              redraw();
              counter++;
              if (counter == plane.length) {
                clearInterval(interval);
              }
            }

            function preload() {
              plane = loadImage('https://147.175.121.210:4480/final/public/img/models/airplane.svg');
              pitch = loadImage('https://147.175.121.210:4480/final/public/img/models/airplane-back.svg');
            }

            function setup() {
              var width = document.getElementById('animationContainer').offsetWidth;
              let myCanvas = createCanvas(width, 300);
              myCanvas.parent('animationContainer');
              baseSize = width * 0.2;
              x = width * 0.5;
              y = height * 0.5;
              startInterval();
            }

            function draw() {
              clear();
              push();
              airplane(x,y,plane_angle);
              airplaneBack(baseSize*0.53, 0, pitch_angle);
              pop();
            }

            function airplane(x,y,rot){
              translate(x,y,rot);
              rotate(rot);
              image(body, -baseSize, -(baseSize*0.57), baseSize*2, baseSize);
            }

            function airplaneBack(x, y, rot) {
              translate(x, y);
              rotate(rot);
              image(back,0,0,baseSize*0.17,baseSize*0.02);
            }

            function windowResized() {
              resizeCanvas(windowWidth, windowHeight);
            }
        </script>
    <?php endif; ?>
<?php endif;?>
