<?php
if (isset($_POST['pdfexport'])) {
    //Never ever! HTML do pdf je najviac smrt v živote
    $url = 'https://localhost:443/final/index.php?p=api';
    $curl = curl_init ($url);
    curl_setopt ($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt ($curl, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt ($curl, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt ($curl, CURLOPT_HTTPHEADER, array("Cookie: language=".$_COOKIE["language"]));
    $page = curl_exec ($curl);
    curl_close ($curl);

    $doc = new DOMDocument('1.0', 'UTF-8');
    libxml_use_internal_errors(true);
    $doc->loadHTML($page);
    libxml_clear_errors();
    $apicontent = $doc->getElementById("apicontent");
    $apicontent = $doc->saveXML($apicontent);

    $text = \Soundasleep\Html2Text::convert($apicontent);

    ob_start();
    $pdf = new tFPDF();
    $pdf->AddPage();
    $pdf->AddFont('AnonymousPro','','AnonymousPro-Regular.ttf',true);
    $pdf->SetFont('AnonymousPro','',8);
    $pdf->write(5,$text);
    $pdf->Output('D','ApiPage.pdf');
    ob_end_flush();

}
?>
<div id="apicontent">
<h1 class="pb-4"><?php Helper::translate($_COOKIE['language'],"api") ?></h1>
<h2><?php Helper::translate($_COOKIE['language'],"invertedPendulum") ?> [GET]</h2>
<label for="invertedpendulum">URL</label>
<input type="text" id="invertedpendulum" class="form-control mb-2" disabled value="https://147.175.121.210:4480/final/api.php?key=(key)&amp;model=invertedpendulum&amp;r=(val)&amp;position=(val)">
<label><?php Helper::translate($_COOKIE['language'],"params") ?>:</label>
<table class="table table-dark table-striped table-hover">
    <thead>
        <tr>
            <th>Argument</th>
            <th><?php Helper::translate($_COOKIE['language'],"params") ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>key</td>
            <td><?php Helper::translate($_COOKIE['language'],"apikey") ?></td>
        </tr>
        <tr>
            <td>model</td>
            <td><?php Helper::translate($_COOKIE['language'],"modelname") ?></td>
        </tr>
        <tr>
            <td>r</td>
            <td><?php Helper::translate($_COOKIE['language'],"rpendulum") ?></td>
        </tr>
        <tr>
            <td>position</td>
            <td><?php Helper::translate($_COOKIE['language'],"initposition") ?></td>
        </tr>
    </tbody>
</table>
<br>
<h2><?php Helper::translate($_COOKIE['language'],"suspension") ?> [GET]</h2>
<label for="suspension">URL</label>
<input type="text" id="suspension" class="form-control mb-2" disabled value="https://147.175.121.210:4480/final/api.php?key=(key)&amp;model=suspension&amp;r=(val)&amp;position=(val)">
<label><?php Helper::translate($_COOKIE['language'],"params") ?>:</label>
<table class="table table-dark table-striped table-hover">
    <thead>
        <tr>
            <th>Argument</th>
            <th><?php Helper::translate($_COOKIE['language'],"params") ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>key</td>
            <td><?php Helper::translate($_COOKIE['language'],"apikey") ?></td>
        </tr>
        <tr>
            <td>model</td>
            <td><?php Helper::translate($_COOKIE['language'],"modelname") ?></td>
        </tr>
        <tr>
            <td>r</td>
            <td><?php Helper::translate($_COOKIE['language'],"rballbeam") ?></td>
        </tr>
        <tr>
            <td>position</td>
            <td><?php Helper::translate($_COOKIE['language'],"initposition") ?></td>
        </tr>
    </tbody>
</table>
<br>
<h2><?php Helper::translate($_COOKIE['language'],"ballbeam") ?> [GET]</h2>
<label for="ballbeam">URL</label>
<input type="text" id="ballbeam" class="form-control mb-2" disabled value="https://147.175.121.210:4480/final/api.php?key=(key)&amp;model=ballbeam&amp;r=(val)&amp;position=(val)">
<label><?php Helper::translate($_COOKIE['language'],"params") ?>:</label>
<table class="table table-dark table-striped table-hover">
    <thead>
        <tr>
            <th>Argument</th>
            <th><?php Helper::translate($_COOKIE['language'],"params") ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>key</td>
            <td><?php Helper::translate($_COOKIE['language'],"apikey") ?></td>
        </tr>
        <tr>
            <td>model</td>
            <td><?php Helper::translate($_COOKIE['language'],"modelname") ?></td>
        </tr>
        <tr>
            <td>r</td>
            <td><?php Helper::translate($_COOKIE['language'],"rsuspension") ?></td>
        </tr>
        <tr>
            <td>position</td>
            <td><?php Helper::translate($_COOKIE['language'],"initposition") ?></td>
        </tr>
    </tbody>
</table>
<br>
<h2><?php Helper::translate($_COOKIE['language'],"aircraftpitch") ?> [GET]</h2>
<label for="aircraftpitch">URL</label>
<input type="text" id="aircraftpitch" class="form-control mb-2" disabled value="https://147.175.121.210:4480/final/api.php?key=(key)&amp;model=aircraftpitch&amp;r=(val)&amp;position=(val)">
<label><?php Helper::translate($_COOKIE['language'],"params") ?>:</label>
<table class="table table-dark table-striped table-hover">
    <thead>
        <tr>
            <th>Argument</th>
            <th><?php Helper::translate($_COOKIE['language'],"params") ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>key</td>
            <td><?php Helper::translate($_COOKIE['language'],"apikey") ?></td>
        </tr>
        <tr>
            <td>model</td>
            <td><?php Helper::translate($_COOKIE['language'],"modelname") ?></td>
        </tr>
        <tr>
            <td>r</td>
            <td><?php Helper::translate($_COOKIE['language'],"raircraft") ?></td>
        </tr>
        <tr>
            <td>position</td>
            <td><?php Helper::translate($_COOKIE['language'],"initposition") ?></td>
        </tr>
    </tbody>
</table>
</div>
<form method="POST">
    <div class="form-group">
        <input type="submit" class="btn btn-primary" name="pdfexport" value="<?php Helper::translate($_COOKIE['language'],'pdfexport') ?>">
    </div>
</form>
