<h1 class="pb-4"><?php Helper::translate($_COOKIE['language'],"api") ?></h1>
<h2><?php Helper::translate($_COOKIE['language'],"invertedPendulum") ?> [GET]</h2>
<label for="invertedpendulum">URL</label>
<input type="text" id="invertedpendulum" class="form-control mb-2" disabled value="https://147.175.121.210:4480/final/api.php?key=(key)&model=invertedpendulum&r=(val)&position=(val)">
<label><?php Helper::translate($_COOKIE['language'],"params") ?></label>
<table class="table table-dark table-striped table-hover">
    <thead>
        <tr>
            <th>Argument</th>
            <th><?php Helper::translate($_COOKIE['language'],"params") ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>key</td>
            <td><?php Helper::translate($_COOKIE['language'],"apikey") ?></td>
        </tr>
        <tr>
            <td>model</td>
            <td><?php Helper::translate($_COOKIE['language'],"modelname") ?></td>
        </tr>
        <tr>
            <td>r</td>
            <td><?php Helper::translate($_COOKIE['language'],"rvalue") ?></td>
        </tr>
        <tr>
            <td>position</td>
            <td><?php Helper::translate($_COOKIE['language'],"initposition") ?></td>
        </tr>
    </tbody>
</table>
<br>
<h2><?php Helper::translate($_COOKIE['language'],"suspension") ?> [GET]</h2>
<label for="invertedpendulum">URL</label>
<input type="text" id="invertedpendulum" class="form-control mb-2" disabled value="https://147.175.121.210:4480/final/api.php?key=(key)&model=suspension&r=(val)&wheel=(val)&car=(val)">
<label><?php Helper::translate($_COOKIE['language'],"params") ?></label>
<table class="table table-dark table-striped table-hover">
    <thead>
        <tr>
            <th>Argument</th>
            <th><?php Helper::translate($_COOKIE['language'],"params") ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>key</td>
            <td><?php Helper::translate($_COOKIE['language'],"apikey") ?></td>
        </tr>
        <tr>
            <td>model</td>
            <td><?php Helper::translate($_COOKIE['language'],"modelname") ?></td>
        </tr>
        <tr>
            <td>r</td>
            <td><?php Helper::translate($_COOKIE['language'],"rvalue") ?></td>
        </tr>
        <tr>
            <td>wheel</td>
            <td><?php Helper::translate($_COOKIE['language'],"initposition") ?></td>
        </tr>
        <tr>
            <td>car</td>
            <td><?php Helper::translate($_COOKIE['language'],"initposition") ?></td>
        </tr>
    </tbody>
</table>
<br>
<h2><?php Helper::translate($_COOKIE['language'],"ballbeam") ?> [GET]</h2>
<label for="invertedpendulum">URL</label>
<input type="text" id="invertedpendulum" class="form-control mb-2" disabled value="https://147.175.121.210:4480/final/api.php?key=(key)&model=ballbeam&r=(val)&angle=(val)&position=(val)">
<label><?php Helper::translate($_COOKIE['language'],"params") ?></label>
<table class="table table-dark table-striped table-hover">
    <thead>
        <tr>
            <th>Argument</th>
            <th><?php Helper::translate($_COOKIE['language'],"params") ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>key</td>
            <td><?php Helper::translate($_COOKIE['language'],"apikey") ?></td>
        </tr>
        <tr>
            <td>model</td>
            <td><?php Helper::translate($_COOKIE['language'],"modelname") ?></td>
        </tr>
        <tr>
            <td>r</td>
            <td><?php Helper::translate($_COOKIE['language'],"rvalue") ?></td>
        </tr>
        <tr>
            <td>position</td>
            <td><?php Helper::translate($_COOKIE['language'],"initposition") ?></td>
        </tr>
        <tr>
            <td>angle</td>
            <td><?php Helper::translate($_COOKIE['language'],"initangle") ?></td>
        </tr>
    </tbody>
</table>
<br>
<h2><?php Helper::translate($_COOKIE['language'],"aircraftpitch") ?> [GET]</h2>
<label for="invertedpendulum">URL</label>
<input type="text" id="invertedpendulum" class="form-control mb-2" disabled value="https://147.175.121.210:4480/final/api.php?key=(key)&model=aircraftpitch&r=(val)&plane=(val)&pitch=(val)">
<label><?php Helper::translate($_COOKIE['language'],"params") ?></label>
<table class="table table-dark table-striped table-hover">
    <thead>
        <tr>
            <th>Argument</th>
            <th><?php Helper::translate($_COOKIE['language'],"params") ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>key</td>
            <td><?php Helper::translate($_COOKIE['language'],"apikey") ?></td>
        </tr>
        <tr>
            <td>model</td>
            <td><?php Helper::translate($_COOKIE['language'],"modelname") ?></td>
        </tr>
        <tr>
            <td>r</td>
            <td><?php Helper::translate($_COOKIE['language'],"rvalue") ?></td>
        </tr>
        <tr>
            <td>plane</td>
            <td><?php Helper::translate($_COOKIE['language'],"initangle") ?></td>
        </tr>
        <tr>
            <td>pitch</td>
            <td><?php Helper::translate($_COOKIE['language'],"initangle") ?></td>
        </tr>
    </tbody>
</table>
<form method="POST">
    <div class="form-group">
        <input type="submit" class="btn btn-primary" name="pdfexport" value="<?php Helper::translate($_COOKIE['language'],'pdfexport') ?>">
    </div>
</form>
<?php
if (isset($_POST['pdfexport'])) {
    $pdf = new Pdf('https://147.175.121.210:4480/final/index.php?p=api');

    if (!$pdf->send('apiPage.pdf')) {
      $error = $pdf->getError();
      // ... handle error here
    }

}
?>
