<?php Db::$medoo->update("stats",["visitors[+]" => 1],["page_name"=>"ballbeam"])?>
<h1><?php Helper::translate($_COOKIE['language'],"ballbeam") ?></h1>
<form method="POST">
    <div class="form-group">
        <label for="angle"><?php Helper::translate($_COOKIE['language'],"angle") ?></label>
        <input type="number" class="form-control" name="angle" id="angle" required>
    </div>
    <div class="form-group">
        <label for="position"><?php Helper::translate($_COOKIE['language'],"position") ?></label>
        <input type="number" class="form-control" name="position" id="position" required>
    </div>
    <div class="form-group">
        <label for="r">r</label>
        <input type="number" class="form-control" name="r" id="r" required>
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="animation" name="animation" value="1" checked>
        <label for="animation"><?php Helper::translate($_COOKIE['language'],"animation") ?></label>
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="graph" name="graph" value="1" checked>
        <label for="graph"><?php Helper::translate($_COOKIE['language'],"graph") ?></label>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" name="send" value="<?php Helper::translate($_COOKIE['language'],'send') ?>">
    </div>
</form>
<?php
if(isset($_POST['send'])):
    $ir = trim($_POST['r']); $ip = trim($_POST['position']); $ia = trim($_POST['angle']);
    $arrContextOptions=array(
        "ssl"=>array(
            "verify_peer"=>false,
            "verify_peer_name"=>false,
        ),
        'http' => array('ignore_errors' => true),
    );
    $arr = file_get_contents("https://localhost:443/final/api.php?key=KHt9t83cmV6pfcyfSbcB9jyG7TnJMySYT28CUv2jSMN9RrNj&model=invertedpendulum&r={$ir}&angle={$ia}&position={$ip}", false, stream_context_create($arrContextOptions));
    $arr = json_decode($arr, true);
    if(isset($_POST['graph']) && $_POST['graph'] = 1): ?>
        <div id="chart"></div>
        <script>
            var chart = new CanvasJS.Chart("chart", {
                animationEnabled: true,
                exportEnabled: true,
                theme: "dark2", // "light1", "light2", "dark1", "dark2"
                zoomEnabled: true,
                title:{
                    text: "<?php Helper::translate($_COOKIE["language"],"ballbeamgraph") ?>"
                },
                data: [{
                    type: "line", //change type to bar, line, area, pie, etc
                    //indexLabel: "{y}", //Shows y value on all Data Points
                    indexLabelFontColor: "#5487c1",
                    indexLabelPlacement: "outside",
                    lineColor: "#5487c1",
                    dataPoints: [{x:0,y:0}]
                },{
                    type: "line", //change type to bar, line, area, pie, etc
                    //indexLabel: "{y}", //Shows y value on all Data Points
                    indexLabelFontColor: "#dc8e39",
                    indexLabelPlacement: "outside",
                    lineColor: "#dc8e39",
                    dataPoints: [{x:0,y:0}]
                }]
            });

            chart.options.data[0].dataPoints = <?= json_encode($arr['position']); ?>;
            chart.options.data[1].dataPoints = <?= json_encode($arr['angle']); ?>;
            chart.render();
        </script>
    <?php endif;
    if(isset($_POST['animation']) && $_POST['animation'] = 1): ?>
        <div id="animation"></div>
        <script>
            let x, y, baseSize, counter = 0;
            let ball_pos = 0;
            let beam_angle = 0;
            var interval;
            var position = <?= json_encode($arr['position']); ?>;
            var angle = <?= json_encode($arr['angle']); ?>;

            function startInterval(){
              interval = setInterval(function(){
                intervalRedraw();
              }, 5000/count(position));
            }

            function intervalRedraw() {
              ball_pos = position[counter]['y'];
              beam_angle = angle[counter]['y'];
              redraw();
              counter++;
              if (counter == count($arr['position'])) {
                clearInterval(interval);
              }
            }

            function preload() {
              ball = loadImage('../../public/img/models/ball.svg');
              beam = loadImage('../../public/img/models/beam.svg');
            }

            function setup() {
              canvas=createCanvas(windowWidth, windowHeight);
              canvas.parent('animation');
              baseSize = width * 0.2;
              x = width * 0.5;
              y = height * 0.5;
            }

            function draw() {
              clear();
              push();
              beamMove(x, y, beam_angle);
              ballMove(0,0, ball_pos);
              pop();
              startInterval();
            }

            function beamMove(x,y,rot){
              translate(x,y,rot);
              rotate(rot);
              image(beam, -(baseSize*1.5), 0, baseSize*3, baseSize*0.1);
            }

            function ballMove(x, y, pos) {
              translate(x, y);
              image(ball,0+pos,-(baseSize*0.4),(baseSize*0.4),(baseSize*0.4));
            }

            function windowResized() {
              resizeCanvas(windowWidth, windowHeight);
            }
        </script>
    <?php endif; ?>
<?php endif;?>
