<h1><?php Helper::translate($_COOKIE['language'],"commands") ?></h1>
<form method="POST">
    <div class="form-group">
        <label for="commands"><?php Helper::translate($_COOKIE['language'],"type_command") ?></label>
        <textarea class="form-control" name="commands" id="commands" rows="3"></textarea>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" name="send" value="<?php Helper::translate($_COOKIE['language'],'send') ?>">
    </div>
</form>

<?php
if(isset($_POST['send'])):
    $command = trim($_POST['commands']);
    $output = ltrim(shell_exec('octave --no-gui --quiet --eval "pkg load control;'. $command .'"'));
    Db::$medoo->insert("commands",[
      "command"=>$command,
      "output"=>$output
    ]);
    ?>
    <div class="form-group">
        <label for="output"><?php Helper::translate($_COOKIE['language'],"output") ?></label>
        <textarea class="form-control" name="output" id="output" rows="3" disabled><?= $output ?></textarea>
    </div>
<?php endif; ?>
