<h1><?php Helper::translate($_COOKIE['language'],"commands") ?></h1>
<form method="POST">
    <div class="form-group">
        <label for="commands"><?php Helper::translate($_COOKIE['language'],"type_command") ?></label>
        <textarea class="form-control" name="commands" id="commands" rows="3"></textarea>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" name="send" value="<?php Helper::translate($_COOKIE['language'],'send') ?>">
    </div>
</form>
<h1><?php Helper::translate($_COOKIE['language'],"exportoption") ?></h1>
<form method="POST">
    <div class="form-group">
        <input type="submit" class="btn btn-primary" name="pdfexport" value="<?php Helper::translate($_COOKIE['language'],'pdfexport') ?>">
    </div>
</form>
<form method="POST">
    <div class="form-group">
        <input type="submit" class="btn btn-primary" name="csvexport" value="<?php Helper::translate($_COOKIE['language'],'csvexport') ?>">
    </div>
</form>

<?php
if(isset($_POST['send'])):
    $command = trim($_POST['commands']);
    $output = ltrim(shell_exec('octave --no-gui --quiet --eval "pkg load control;'. $command .'"'));
    Db::$medoo->insert("commands",[
      "command"=>$command,
      "output"=>$output
    ]);
    ?>
    <div class="form-group">
        <label for="output"><?php Helper::translate($_COOKIE['language'],"output") ?></label>
        <textarea class="form-control" name="output" id="output" rows="3" disabled><?= $output ?></textarea>
    </div>
<?php endif;
if (isset($_POST['pdfexport'])) {
    ob_start();
    $result = Db::$medoo->select("commands",["date","command","output","success","error"],[]);
    $header = array('Date','Command','Output',"Success","Error");

    $pdf = new tFPDF();
    $pdf->AddPage();
    $pdf->AddFont('AnonymousPro','','AnonymousPro-Regular.ttf',true);
    $pdf->SetFont('AnonymousPro','',8);

    $pdf->Cell(34,5,$header[0],1);
    $pdf->Cell(87,5,$header[1],1);
    $pdf->Cell(34,5,$header[2],1);
    $pdf->Cell(17,5,$header[3],1);
    $pdf->Cell(17,5,$header[4],1);

    foreach($result as $row) {
      $pdf->Ln();
      $pdf->Cell(34,5,$row["date"],1);
      $pdf->Cell(87,5,$row["command"],1);
      $pdf->Cell(34,5,$row["output"],1);
      $pdf->Cell(17,5,$row["success"],1);
      $pdf->Cell(17,5,$row["error"],1);
    }
    $pdf->Output('D','commandlog.pdf');
    ob_end_flush();
}
if (isset($_POST['csvexport'])) {
    $result = Db::$medoo->select("commands",["date","command","output","success","error"],[]);

    ob_clean();
    ob_start();
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename=commandlog.csv');
    $output = fopen('php://output', 'w');
    fputcsv($output, array('Date', 'Command', 'Output',"Success","Error"));
    if (count($result) > 0) {
        foreach ($result as $row) {
            fputcsv($output, $row);
        }
    }
    ob_end_flush();
    die();
}
?>
