<h1><?php Helper::translate($_COOKIE['language'],"technicaldoc") ?></h1>

<h2>URL:</h2>
<p><a href="https://147.175.121.210:4480/final/index.php">https://147.175.121.210:4480/final/index.php</a></p>
<h2>PhpMyAdmin:</h2>
<p><a href="https://147.175.121.210:4480/phpmyadmin/index.php">https://147.175.121.210:4480/phpmyadmin/index.php</a></p>

<h2><?php Helper::translate($_COOKIE['language'],"install") ?>:</h2>
<p>sudo add-apt-repository ppa:octave/stable<br>
    sudo apt-get update<br>
    sudo apt-get install octave<br>
    octave<br>
    pkg install -global -forge control<br>
</p>