<h1><?php Helper::translate($_COOKIE['language'],"information") ?></h1>
<p>
    <?php Helper::translate($_COOKIE['language'],"informationtext") ?>
</p>
<h1 class="sitemap-title"><?php Helper::translate($_COOKIE['language'],"sitemap") ?></h1>
<p class="sitemap"><?php Helper::translate($_COOKIE['language'],"information") ?></p>
<p class="sitemap-detail"><?php Helper::translate($_COOKIE['language'],"sitemapinformation") ?></p>
<p class="sitemap"><?php Helper::translate($_COOKIE['language'],"models") ?></p>
<p class="sitemap-detail"><?php Helper::translate($_COOKIE['language'],"sitemapmodel") ?></p>
<p class="sitemap-child"><?php Helper::translate($_COOKIE['language'],"invertedPendulum") ?></p>
<p class="sitemap-child-detail"><?php Helper::translate($_COOKIE['language'],"sitemapmodelpendulum") ?></p>
<p class="sitemap-child"><?php Helper::translate($_COOKIE['language'],"suspension") ?></p>
<p class="sitemap-child-detail"><?php Helper::translate($_COOKIE['language'],"sitemapmodelsuspension") ?></p>
<p class="sitemap-child"><?php Helper::translate($_COOKIE['language'],"ballbeam") ?></p>
<p class="sitemap-child-detail"><?php Helper::translate($_COOKIE['language'],"sitemapmodelballbeam") ?></p>
<p class="sitemap-child"><?php Helper::translate($_COOKIE['language'],"aircraftpitch") ?></p>
<p class="sitemap-child-detail"><?php Helper::translate($_COOKIE['language'],"sitemapaircraft") ?></p>
<p class="sitemap"><?php Helper::translate($_COOKIE['language'],"commands") ?></p>
<p class="sitemap-detail"><?php Helper::translate($_COOKIE['language'],"sitemapcommands") ?></p>
<p class="sitemap"><?php Helper::translate($_COOKIE['language'],"api") ?></p>
<p class="sitemap-detail"><?php Helper::translate($_COOKIE['language'],"sitemapapi") ?></p>
<p class="sitemap"><?php Helper::translate($_COOKIE['language'],"stats") ?></p>
<p class="sitemap-detail"><?php Helper::translate($_COOKIE['language'],"sitemapstats") ?></p>
<p class="sitemap"><?php Helper::translate($_COOKIE['language'],"tasks") ?></p>
<p class="sitemap-detail"><?php Helper::translate($_COOKIE['language'],"sitemaptasks") ?></p>
