<h1><?php Helper::translate($_COOKIE['language'],"information") ?></h1>
<p>Tento projekt bol vytvorený v spoluprácií 4 žiakov FEI STU.... blablabla Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<h1 class="sitemap-title"><?php Helper::translate($_COOKIE['language'],"sitemap") ?></h1>
<p class="sitemap"><?php Helper::translate($_COOKIE['language'],"information") ?></p>
<p class="sitemap-detail">Obsahuje informácie o stránkach a výslednom projekte</p>
<p class="sitemap"><?php Helper::translate($_COOKIE['language'],"models") ?></p>
<p class="sitemap-detail">Obsahuje vypracované modely spolu s grafmi a textovým poľom na simuláciu jednotlivých zariadení</p>
<p class="sitemap-child"><?php Helper::translate($_COOKIE['language'],"invertedPendulum") ?></p>
<p class="sitemap-child-detail">Punúka grafickú simuláciu prevrateného kyvadla</p>
<p class="sitemap-child"><?php Helper::translate($_COOKIE['language'],"suspension") ?></p>
<p class="sitemap-child-detail">Punúka grafickú simuláciu tlmiča na automobile</p>
<p class="sitemap-child"><?php Helper::translate($_COOKIE['language'],"ballbeam") ?></p>
<p class="sitemap-child-detail">Punúka grafickú simuláciu guličky na tyči</p>
<p class="sitemap-child"><?php Helper::translate($_COOKIE['language'],"aircraftpitch") ?></p>
<p class="sitemap-child-detail">Punúka grafickú simuláciu lietadlovej klapky</p>
<p class="sitemap"><?php Helper::translate($_COOKIE['language'],"commands") ?></p>
<p class="sitemap-detail">Obsahuje "príkazový" riadok do ktorého je možné vpisovať príkazy, ktoré budu následne spracované. Taktiež sa tu nachádza voľba exportu príkazov, ktoré boli odosielané do CAS, vo formáte PDF a CSV.</p>
<p class="sitemap"><?php Helper::translate($_COOKIE['language'],"api") ?></p>
<p class="sitemap-detail">Obsahuje popis vytvoreného api spolu s príkladom URL adresy a s popisom jednotlivých parametrov. Na tejto podsránke je možné si danú API dokumentáciu stiahnuť vo formáte PDF.</p>
<p class="sitemap"><?php Helper::translate($_COOKIE['language'],"stats") ?></p>
<p class="sitemap-detail">Obsahuje štatistiky robrazenia jednotlivých modelov. Ponúka možnosť zaslania týchto infomácii na vybraný email.</p>
<p class="sitemap"><?php Helper::translate($_COOKIE['language'],"tasks") ?></p>
<p class="sitemap-detail">Obsahuje tabuľku rozdelenia úloh spolu s člemni, ktorý danú úlohu vypracovali.</p>
