<?php
if(isset($_GET['lang'])) {
    Helper::setLanguage($_GET['lang']);
    Helper::route("");
}
?>

<!doctype html>
<html lang="sk">
<head>
    <title>Final task</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?= Asset::get('css/bootstrap.min.css') ?>" type="text/css">
    <link rel="stylesheet" href="<?= Asset::get('css/custom.css') ?>" type="text/css">
    <script src="<?= Asset::get('js/jquery-3.1.1.min.js') ?>"></script>
    <script src="<?= Asset::get('js/popper.min.js') ?>"></script>
    <script src="<?= Asset::get('js/bootstrap.min.js') ?>"></script>
    <script src="<?= Asset::get('js/main.js') ?>"></script>
    <script src="<?= Asset::get('js/animation.min.js') ?>"></script>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</head>

<?php
include_once('app/view/nav.phtml');
?>

<div class="content-wrapper">
    <div class="container">
        <?php
        Router::writeContent("content");
        ?>
    </div>
</div>
<footer class="bg-dark">
    Copyright (c) Vladislav Domin
</footer>
