<h1><?php Helper::translate($_COOKIE['language'],"stats") ?></h1>
<table class="table table-dark table-striped table-hover">
    <thead>
        <tr>
            <th><?php Helper::translate($_COOKIE['language'],"invertedPendulum") ?></th>
            <th><?php Helper::translate($_COOKIE['language'],"suspension") ?></th>
            <th><?php Helper::translate($_COOKIE['language'],"ballbeam") ?></th>
            <th><?php Helper::translate($_COOKIE['language'],"aircraftpitch") ?></th>
        </tr>
    </thead>
    <tbody>
        <tr class="stats">
            <td><?= Db::$medoo->get("stats","visitors",["page_name"=>"pendulum"])?></td>
            <td><?= Db::$medoo->get("stats","visitors",["page_name"=>"suspension"])?></td>
            <td><?= Db::$medoo->get("stats","visitors",["page_name"=>"ballbeam"])?></td>
            <td><?= Db::$medoo->get("stats","visitors",["page_name"=>"aircraftpitch"])?></td>
        </tr>
    </tbody>
</table>
<br>
<h1><?php Helper::translate($_COOKIE['language'],"statsemailsend") ?></h1>
<form method="POST">
    <div class="form-group">
        <label for="email">E-mail:</label>
        <input type="text" class="form-control" name="email" id="email" required>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" name="send" value="<?php Helper::translate($_COOKIE['language'],'send') ?>">
    </div>
</form>
<?php
if (isset($_POST["send"]) && isset($_POST["email"]))
{
  $content = "
  <html><body>
  <h2>WEBTE2-final statistics</h2>
  <p>Inverted pendulum: ". Db::$medoo->get("stats","visitors",["page_name"=>"pendulum"]) ."</p>
  <p>Suspension: " . Db::$medoo->get("stats","visitors",["page_name"=>"suspension"]) . "</p>
  <p>Ball & beam: " . Db::$medoo->get("stats","visitors",["page_name"=>"ballbeam"]) . "</p>
  <p>Aircraft pitch: " . Db::$medoo->get("stats","visitors",["page_name"=>"aircraftpitch"]) . "</p>
  <br>
  <p>Send from WEBTE2-final page created by Vladislav Domin, Viktória Dominová, Peter Bašista, Eliška Bakaľárová</p>
  </body></html>
  ";
    // Create the Transport
    $transport = (new Swift_SmtpTransport('smtp.websupport.sk', 25, 'tls'))
        ->setUsername('test@v-d.sk')
        ->setPassword('Ac6odIJ?{^')
    ;

// Create the Mailer using your created Transport
    $mailer = new Swift_Mailer($transport);

// Create a message
    $message = (new Swift_Message('WEBTECH2 FINAL - STATS'))
        ->setFrom(['test@v-d.sk' => 'WEBTECH FINAL 2'])
        ->setTo([$_POST['email'], $_POST['email'] => 'A name'])
        ->setBody($content, 'text/html');
// Send the message
    $result = $mailer->send($message);
}
?>
