<?php Db::$medoo->update("stats",["visitors[+]" => 1],["page_name"=>"suspension"])?>
<h1><?php Helper::translate($_COOKIE['language'],"suspension") ?></h1>
<form method="POST">
    <div class="form-group">
        <label for="r">Výška skokovej prekážky</label>
        <input type="number" class="form-control" name="r" id="r" step="0.01" required autocomplete="off">
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="animation" name="animation" value="1" checked>
        <label for="animation"><?php Helper::translate($_COOKIE['language'],"animation") ?></label>
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="graph" name="graph" value="1" checked>
        <label for="graph"><?php Helper::translate($_COOKIE['language'],"graph") ?></label>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" name="send" value="<?php Helper::translate($_COOKIE['language'],'send') ?>">
    </div>
</form>
<?php
if(isset($_POST['send'])):
    $ir = trim($_POST['r']);
    $arrContextOptions=array(
        "ssl"=>array(
            "verify_peer"=>false,
            "verify_peer_name"=>false,
        ),
        'http' => array('ignore_errors' => true),
    );
    $arr = file_get_contents("https://localhost:443/final/api.php?key=KHt9t83cmV6pfcyfSbcB9jyG7TnJMySYT28CUv2jSMN9RrNj&model=suspension&r={$ir}&position={$_SESSION['suspension']}", false, stream_context_create($arrContextOptions));
    $arr = json_decode($arr, true);
    $animation = (isset($_POST['animation'])) ? '; animation' : '';
    $graph = (isset($_POST['graph'])) ? '; graph' : '';
    Db::$medoo->insert("commands",[
      "command"=>"Suspension -> r = " . $_POST['r'] . $animation . $graph,
      "output"=> gettype($arr),
      "success" => "1"
    ]);
    $_SESSION['suspension'] = $arr['continue'];
    if(isset($_POST['animation']) && $_POST['animation'] = 1): ?>
        <div id='animationContainer' class="animation"></div>
        <script>
            // nastavenie dlzky animacie
            var time = 5000;
            // nastavenie koeficientu prepočtu pohybu, rýchlosť pohybu "car" and "wheel"
            var coeficient = 20;

            let wheel_pos = 0;
            let sus_pos = 0;
            var wheel_position = <?= json_encode($arr['wheel']); ?>;
            var car_position = <?= json_encode($arr['car']); ?>;
            let x, y, baseSize, counter = 0;
            var interval;

            function startInterval(){
              interval = setInterval(function(){
                intervalRedraw();
              }, time/wheel_position.length);
            }

            function intervalRedraw() {
              wheel_pos = wheel_position[counter]['y'];
              sus_pos = car_position[counter]['y'];
              redraw();
              counter++;
              if (counter == wheel_position.length) {
                clearInterval(interval);
              }
            }

            function preload() {
              wheel = loadImage('https://147.175.121.210:4480/final/public/img/models/wheel.svg');
              suspension = loadImage('https://147.175.121.210:4480/final/public/img/models/suspension.svg');
            }

            function setup() {
              var width = document.getElementById('animationContainer').offsetWidth;
              let myCanvas = createCanvas(width, 300);
              myCanvas.parent('animationContainer');
              baseSize = height * 0.5;
              x = width * 0.46;
              y = height * 0.4;
              startInterval();
            }

            function draw() {
              clear();
              push();
              susMove(x, y, sus_pos*coeficient);
              wheelMove(0,0,wheel_pos);
              pop();
            }

            function wheelMove(x,y,pos){
              translate(x,y);
              image(wheel, -(baseSize*0.3), -(baseSize*0.05)+pos, baseSize, baseSize);
            }

            function susMove(x, y, pos) {
              translate(x, y);
              image(suspension,0,-(baseSize/2)+pos,baseSize*0.4,baseSize);
            }

            function windowResized() {
              resizeCanvas(windowWidth, windowHeight);
            }
        </script>
    <?php endif;
    if(isset($_POST['graph']) && $_POST['graph'] = 1): ?>
        <div id="chart" class="graph"></div>
        <script>
            var chart = new CanvasJS.Chart("chart", {
                animationEnabled: true,
                exportEnabled: true,
                theme: "dark2", // "light1", "light2", "dark1", "dark2"
                zoomEnabled: true,
                title:{
                    text: "<?php Helper::translate($_COOKIE["language"],"suspensiongraph") ?>"
                },
                data: [{
                    type: "line", //change type to bar, line, area, pie, etc
                    //indexLabel: "{y}", //Shows y value on all Data Points
                    indexLabelFontColor: "#5487c1",
                    indexLabelPlacement: "outside",
                    lineColor: "#5487c1",
                    dataPoints: [{x:0,y:0}]
                },{
                    type: "line", //change type to bar, line, area, pie, etc
                    //indexLabel: "{y}", //Shows y value on all Data Points
                    indexLabelFontColor: "#dc8e39",
                    indexLabelPlacement: "outside",
                    lineColor: "#dc8e39",
                    dataPoints: [{x:0,y:0}]
                }]
            });

            chart.options.data[0].dataPoints = <?= json_encode($arr['wheel']); ?>;
            chart.options.data[1].dataPoints = <?= json_encode($arr['car']); ?>;
            chart.render();
        </script>
    <?php endif; ?>
<?php endif;?>
