<h1><?php Helper::translate($_COOKIE['language'],"tasks") ?></h1>

<table class="table table-dark table-hover table-striped">
    <thead>
        <tr>
          <th><?php Helper::translate($_COOKIE['language'],"task") ?></th>
          <th><?php Helper::translate($_COOKIE['language'],"creator") ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php Helper::translate($_COOKIE['language'],"webbase") ?></td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td><?php Helper::translate($_COOKIE['language'],"design") ?></td>
            <td>Viktória Dominová</td>
        </tr>
        <tr>
            <td><?php Helper::translate($_COOKIE['language'],"multilanguage") ?></td>
            <td>Peter Bašista</td>
        </tr>
        <tr>
            <td><?php Helper::translate($_COOKIE['language'],"api") ?></td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td><?php Helper::translate($_COOKIE['language'],"subpage_content") ?></td>
            <td>Eliška Bakaľárová</td>
        </tr>
        <tr>
            <td><?php Helper::translate($_COOKIE['language'],"com_web_octave") ?></td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td><?php Helper::translate($_COOKIE['language'],"log") ?></td>
            <td>Peter Bašista</td>
        </tr>
        <tr>
            <td><?php Helper::translate($_COOKIE['language'],"emailSend") ?></td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td><?php Helper::translate($_COOKIE['language'],"pdfexport") ?></td>
            <td>Peter Bašista</td>
        </tr>
        <tr>
            <td><?php Helper::translate($_COOKIE['language'],"csvexport") ?></td>
            <td>Peter Bašista</td>
        </tr>
        <tr>
            <td><?php Helper::translate($_COOKIE['language'],"invertedPendulum") ?></td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td><?php Helper::translate($_COOKIE['language'],"ballbeam") ?></td>
            <td>Viktória Dominová</td>
        </tr>
        <tr>
            <td><?php Helper::translate($_COOKIE['language'],"suspension") ?></td>
            <td>Peter Bašista</td>
        </tr>
        <tr>
            <td><?php Helper::translate($_COOKIE['language'],"aircraftpitch") ?></td>
            <td>Eliška Bakaľárová</td>
        </tr>
    </tbody>
</table>
