<h1 class="pb-4">API</h1>
<h2>Inverzné kyvadlo [GET]</h2>
<label for="invertedpendulum">URL</label>
<input type="text" id="invertedpendulum" class="form-control mb-2" disabled value="https://147.175.121.210:4480/final/api.php?key=(key)&model=invertedpendulum&r=(val)&position=(val)&angle=(val)">
<label>Parametre</label>
<table class="table table-dark table-striped table-hover">
    <thead>
        <tr>
            <th>Argument</th>
            <th>Popis</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>key</td>
            <td>Kľúč pre overenie</td>
        </tr>
        <tr>
            <td>model</td>
            <td>Názov modelu</td>
        </tr>
        <tr>
            <td>r</td>
            <td>Hodnota "R"</td>
        </tr>
        <tr>
            <td>position</td>
            <td>Inicializačná pozícia</td>
        </tr>
        <tr>
            <td>angle</td>
            <td>Inicializačný uhol</td>
        </tr>
    </tbody>
</table>