<h1>Rozdelenie úloh</h1>

<table class="table table-dark table-hover table-striped">
    <thead>
        <tr>
            <th>Úloha</th>
            <th>Vyhotoviteľ</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Základná štruktúra webu</td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td>Dizajn</td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td>Multijazyčnosť</td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td>API</td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td>Obsah podstránok</td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td>Komunikácia WEB <=> Octave</td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td>Logovanie</td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td>Odosielanie na mail</td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td>Export do PDF</td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td>Export do CSV</td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td>Inverzné kyvadlo</td>
            <td>Vladislav Domin</td>
        </tr>
        <tr>
            <td>Gulička na tyči</td>
            <td>Viktória Dominová</td>
        </tr>
        <tr>
            <td>Tlmič na automobile</td>
            <td>Peter Bašista</td>
        </tr>
        <tr>
            <td>Náklon lietadla</td>
            <td>Eliška Bakaľárová</td>
        </tr>
    </tbody>
</table>