<h1>Tasks</h1>

<table class="table table-dark table-hover table-striped">
    <thead>
    <tr>
        <th>Task</th>
        <th>Author</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Basic structure of web</td>
        <td>Vladislav Domin</td>
    </tr>
    <tr>
        <td>Design</td>
        <td>Vladislav Domin</td>
    </tr>
    <tr>
        <td>Multilanguage support</td>
        <td>Vladislav Domin</td>
    </tr>
    <tr>
        <td>API</td>
        <td>Vladislav Domin</td>
    </tr>
    <tr>
        <td>Content of subpages</td>
        <td>Vladislav Domin</td>
    </tr>
    <tr>
        <td>Communication WEB <=> Octave</td>
        <td>Vladislav Domin</td>
    </tr>
    <tr>
        <td>Logging</td>
        <td>Vladislav Domin</td>
    </tr>
    <tr>
        <td>Emailing</td>
        <td>Vladislav Domin</td>
    </tr>
    <tr>
        <td>Export to PDF</td>
        <td>Vladislav Domin</td>
    </tr>
    <tr>
        <td>Export to CSV</td>
        <td>Vladislav Domin</td>
    </tr>
    <tr>
        <td>Inverse pendulum</td>
        <td>Vladislav Domin</td>
    </tr>
    <tr>
        <td>Ball beam</td>
        <td>Viktória Dominová</td>
    </tr>
    <tr>
        <td>Car suspension</td>
        <td>Peter Bašista</td>
    </tr>
    <tr>
        <td>Aircraft pitch</td>
        <td>Eliška Bakaľárová</td>
    </tr>
    </tbody>
</table>